clues = [
	"frequent Frazier foe",
	"type of magazine you might start getting in your 20's",
	"arguably, the story of our time (and a hint to answering all the other clues...)",
	"stage name of a famous skeptic (with \"The\")",
	"Oscar-winning role from the 80's",
	"often-inset pair, for short",
	"microwaveable snack brand that replaced a refrigerated product",
	"where to find \"take thou this vial\" and \"double, double toil and trouble\"",
	"you might break it in Kabul",
	"eponym of multiple continents (and the answer that should come last after sorting)",
	"onetime Outkast output",
	"notable 2026 launch",
	"the present, in the past",
	"our nearest neighbors, in some sense (though we haven't visited yet...)",
]